name: CI/CD, woo!
on:
  push:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: What's installed now
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Path ~/.local/share/powershell/Modules/ | Select-Object FullName
          Get-ChildItem -Recurse -Path /opt/microsoft/powershell/7/Modules/ | Select-Object FullName
