name: Next up!
on:
  push:
    branches:
      - main
      - test
defaults:
  run:
    shell: pwsh

jobs:
  list-repo-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Just one line
        run: Get-ChildItem -Recurse -Path ./

  list-windows-files:
    runs-on: windows-latest
    steps:
      - name: List C drive
        run: Get-ChildItem C:\
